CREATE TABLE USER
(
    ID NUMBER(*) PRIMARY KEY NOT NULL,
    LASTNAME VARCHAR2(32) NOT NULL,
    FIRSTNAME VARCHAR2(255) NOT NULL,
    BANK VARCHAR2(32)
);

CREATE TABLE CARD
(
    ID NUMBER(*) PRIMARY KEY NOT NULL,
    CARD VARCHAR2(32) NOT NULL,
    PASSWORD VARCHAR2(255) NOT NULL,
    CREATED_AT DATE NOT NULL,
    USER_ID NUMBER(*) NOT NULL,
    CONSTRAINT OPERATION_USER_ID_FK FOREIGN KEY (USER_ID) REFERENCES "USER" (ID)
);

CREATE TABLE OPERATION
(
    ID NUMBER(*) PRIMARY KEY NOT NULL,
    BALANCE FLOAT(126) NOT NULL,
    CARD_ID NUMBER(*) NOT NULL,
    CONSTRAINT OPERATION_CARD_ID_FK FOREIGN KEY (CARD_ID) REFERENCES CARD (ID)
);