CREATE USER atm IDENTIFIED BY atm;

ALTER USER atm DEFAULT TABLESPACE users;

GRANT CONNECT, RESOURCE TO atm;

GRANT EXECUTE ON DBMS_CRYPTO TO ATM;

-- connect as atm/atm --

CREATE TABLE USERS
(
    ID NUMBER(*) PRIMARY KEY NOT NULL,
    LASTNAME VARCHAR2(32) NOT NULL,
    FIRSTNAME VARCHAR2(255) NOT NULL,
    BANK VARCHAR2(32),
    CREATED_AT DATE NOT NULL
);

CREATE TABLE CARD
(
    ID NUMBER(*) PRIMARY KEY NOT NULL,
    CARD VARCHAR2(32) NOT NULL,
    PASSWORD VARCHAR2(255) NOT NULL,
    CREATED_AT DATE NOT NULL,
    USER_ID NUMBER(*) NOT NULL,
    CONSTRAINT OPERATION_USER_ID_FK FOREIGN KEY (USER_ID) REFERENCES "USERS" (ID)
);

CREATE TABLE OPERATION
(
    ID NUMBER(*) PRIMARY KEY NOT NULL,
    BALANCE FLOAT(126) NOT NULL,
    CARD_ID NUMBER(*) NOT NULL,
    CREATED_AT DATE NOT NULL,
    CONSTRAINT OPERATION_CARD_ID_FK FOREIGN KEY (CARD_ID) REFERENCES CARD (ID)
);

CREATE OR REPLACE FUNCTION MD5(P_STR VARCHAR2) RETURN RAW IS
BEGIN
    RETURN LOWER(TO_CHAR(RAWTOHEX(DBMS_CRYPTO.HASH(utl_i18n.string_to_raw(p_str, 'AL32UTF8'), DBMS_CRYPTO.HASH_MD5))));
END MD5;

CREATE OR REPLACE FUNCTION SHA1(P_STR VARCHAR2) RETURN RAW IS
BEGIN
    RETURN LOWER(TO_CHAR(RAWTOHEX(DBMS_CRYPTO.HASH(utl_i18n.string_to_raw(p_str || TO_CHAR(CURRENT_DATE, 'MM-DD-YYYY HH24:MI'), 'AL32UTF8'), DBMS_CRYPTO.HASH_SH1))));
END SHA1;

INSERT INTO CARD(ID, CARD, PASSWORD, CREATED_AT, USER_ID) VALUES(1, '6666666666666666', '8ea15a38c4c1a177d509c85ef6623e23', TO_DATE('2003/05/03 21:02:44', 'yyyy/mm/dd hh24:mi:ss'), 1);

INSERT INTO USERS(ID, LASTNAME, FIRSTNAME, BANK, CREATED_AT) VALUES(1, 'Fabien', 'Beaujean', 'intern', TO_DATE('2003/05/03 21:02:44', 'yyyy/mm/dd hh24:mi:ss'));